### ISSUE TITLE
HTML Cleanup

### ISSUE THREAD

**Issue by davelab6** [typophile/typophile.github.io#1]
For `typophile.com/cms/node/${number}.html` pages

- [x] Remove everything between and inclusive of 

    
    ...
    

- [x] Get forum section and post subject here,

```html
<html>
<div id="wrapper">
    <div id="content-frame">
        <div class="main-content" id="content-none">
            <div id="headline">
              <div class="breadcrumb">
                <a href="/web/20100622054851/http://typophile.com/">Home</a> » 
                <a href="/web/20100622054851/http://typophile.com/forums">Forums</a> » 
                <a href="/web/20100622054851/http://typophile.com/forum/6">Build</a>
              </div>
              <h2 class="content-title">XeLaTeX and OT fonts</h2>
            </div>
```

- [x] get the first post here

```html
<html>
<div id="wrapper">
    <div id="content-frame">
        <div class="main-content" id="content-none">
            <div class="node node-forum">
```

- [ ] Get the comments here

```html
<html>
<div id="wrapper">
    <div id="content-frame">
        <div class="main-content" id="content-none">
            <div class="comments">
                <div class="comment">
```

**Comment by simoncozens** [comment]
I'm going to convert the HTML to JSON rather than MarkDown directly, so that we can maintain the structure (title, author name, date, etc.) for potentially seeding another CMS later.

**Comment by davelab6** [comment]
Scripts to convert the downloaded set are great!

I'm still downloading everything...

```
$ wc -l typophile.github.io/urls-unique.txt 
  212264 typophile.github.io/urls-unique.txt
$ find typophile.com | wc -l
  160261
```

**Comment by davelab6** [comment]
> JSON

I wonder that [protocolbuffer text format](https://developers.google.com/protocol-buffers/docs/proto3#json), or [capn-proto](https://capnproto.org/language.html) might be better

**Comment by simoncozens** [comment]
I doubt it; if there are any CMSes which natively import those formats, then maybe. But I don't think there are. So we will have to write something custom anyway, in which case simpler is better.

**Comment by davelab6** [comment]
Fair enough :D
