### ISSUE TITLE
Resuming feature

### ISSUE THREAD

**Issue by davelab6** [typophile/typophile.github.io#5]
I have downloaded 90% of the archive, so I guess now I need some kind of resuming feature that will only fetch the parts I don't have.... 

    wc -l urls-unique.txt 
    212264 urls-unique.txt
    ./wayback-typophile.pl < urls-unique.txt > output
    wc -l output 
    204575 output

:sos:

**Comment by davelab6** [comment]
:8ball:

**Comment by davelab6** [comment]
Sometimes I get strange lines where it has several `->` and either a http: url on the end, like this

    typophile.com/cgibin/board-profile.pl?action=editpost&page=4101/36168&postid=61156 -> typophile.com/cgibin/board-profile.pl?action=editpost&page=4101/36168&postid=61165 -> http://web.archive.org/20051203032106/http%3A%2F%2Ftypophile.com%2Fcgibin%2Fboard-profile.pl%3Faction%3Deditpost%26page%3D4101%2F36168%26postid%3D61165

or the final line before the program exits with a `->` on the end and no http: in the whole line

    typophile.com/wiki/italic -> typophile.com/wiki/oblique -> typophile.com/wiki/start -> typophile.com/wiki/trajan -> bodas.typophile.com/node/101267 -> fantasmesetfrissons.typophile.com/files/favicon.ico -> fantasmesetfrissons.typophile.com/files/typophiletwitter.png -> fantasmesetfrissons.typophile.com/node/121662 -> smtp.typophile.com/user/11675 -> ww.typophile.com/node/103731 ->

**Comment by davelab6** [comment]
It would also be good to know when the entire archive has been downloaded (as that is really the point of the script.) My copy so far is 6.2Gb, or more precisely in kb:

    $ du -c -k typophile.com | grep total
    6490336	total

**Comment by simoncozens** [comment]
There's a limit to how ornate one should make a script that's only intended to be used once... :-)

**Comment by davelab6** [comment]
I get that. But I am not sure I have everything. How can I be sure?
